/** Robocode Tank Royale physics constants and helpers. */

export const MAX_SPEED = 8;
export const BOT_RADIUS = 18;

/** Bullet speed as a function of firepower: 20 - 3*power. */
export const bulletSpeed = (power: number): number => 20 - 3 * power;

/** Damage a bullet of the given power deals. */
export const bulletDamage = (power: number): number => 4 * power + (power > 1 ? 2 * (power - 1) : 0);

/** Energy returned to the shooter on a hit. */
export const bulletGain = (power: number): number => 3 * power;

/** Gun heat generated by firing: 1 + power/5. */
export const gunHeat = (power: number): number => 1 + power / 5;

/**
 * Maximum escape angle (radians): the widest angle off the firing line an enemy
 * can reach by driving flat-out at MAX_SPEED while the bullet travels. This is
 * the denominator that turns a lateral offset into a GuessFactor in [-1, 1].
 */
export const maxEscapeAngle = (bSpeed: number): number => Math.asin(MAX_SPEED / bSpeed);

/** Deceleration magnitude (units/turn) at a given absolute speed. */
export const decel = (speed: number): number => Math.min(2, Math.max(1, 1 + speed / 2));

/**
 * Next velocity given desired travel direction `dir` (-1 back, 0 stop, +1 fwd),
 * mirroring the real game's accelerate-by-1 / brake-by-up-to-2 rules. Surf
 * prediction must use THIS, not wishful +1s — otherwise we dodge into bullets.
 */
export function nextVelocity(v: number, dir: number): number {
  if (dir === 0) {
    const d = Math.min(decel(Math.abs(v)), Math.abs(v));
    return v - Math.sign(v) * d;
  }
  const inc = Math.sign(v) * dir < 0 ? decel(Math.abs(v)) : 1;
  const nv = v + dir * inc;
  return Math.max(-MAX_SPEED, Math.min(MAX_SPEED, nv));
}

/** Max body turn rate (deg/turn) at a given speed. */
export const maxTurnRate = (speed: number): number => 10 - 0.75 * Math.abs(speed);
