/**
 * Robocode Tank Royale game physics.
 * See https://robocode.dev/articles/intro.html and the Constants in the bot API.
 *
 * All angles here are in DEGREES to match the Tank Royale API.
 */
import { clip, sign } from "./geom.ts";

export const MAX_SPEED = 8;
export const MIN_BULLET_SPEED = 11; // firepower 3
export const MAX_BULLET_SPEED = 19.7; // firepower 0.1
export const MAX_TURN_RATE = 10; // deg/turn at speed 0
export const MAX_GUN_TURN_RATE = 20;
export const MAX_RADAR_TURN_RATE = 45;
export const BOT_RADIUS = 18; // bounding-circle radius
export const ACCELERATION = 1;
export const DECELERATION = 2;

/** Deceleration magnitude (units/turn) at a given absolute speed. */
export function decel(speed: number): number {
  return clip(1 + speed / 2, 1, 2);
}

/**
 * Next velocity given a desired travel direction `dir` (-1 back, 0 stop, +1 forward).
 * Mirrors Robocode's acceleration (+1/turn) / deceleration (up to -2/turn) rules.
 */
export function nextVelocity(v: number, dir: number): number {
  if (dir === 0) {
    return v - sign(v) * Math.min(decel(Math.abs(v)), Math.abs(v));
  }
  // decelerating when the desired direction opposes current velocity
  const inc = sign(v) * dir < 0 ? decel(Math.abs(v)) : ACCELERATION;
  return clip(v + dir * inc, -MAX_SPEED, MAX_SPEED);
}

/** Maximum body turn rate (deg/turn) at a given absolute speed. */
export function maxTurnRate(v: number): number {
  return MAX_TURN_RATE - 0.75 * Math.abs(v);
}

/** Bullet speed (units/turn) for a given firepower. */
export function bulletSpeed(power: number): number {
  return 20 - 3 * clip(power, 0.1, 3);
}

/** Damage dealt by a bullet of the given firepower. */
export function bulletDamage(power: number): number {
  return 4 * power + Math.max(2 * (power - 1), 0);
}

/** Energy gained by the shooter when a bullet of the given power connects. */
export function bulletHitBonus(power: number): number {
  return 3 * power;
}

/** Gun heat generated by firing at the given power. */
export function gunHeat(power: number): number {
  return 1 + power / 5;
}

/** Firepower needed to (just) produce a given bullet speed. */
export function powerFromBulletSpeed(speed: number): number {
  return (20 - speed) / 3;
}
